version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    rules:
      - path: api/
        linters:
          - lll
      - path: internal/
        linters:
          - dupl
          - lll
    paths:
      - third_party
      - examples
      - images
